apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary  # 自定义的Rollout名称
spec:
  replicas: 5  # 定义5个副本
  strategy:  # 定义升级策略
    canary:   # 灰度（金丝雀）发布
      #maxSurge: 5
      #maxUnavailable: 1
      steps:
      - setWeight: 20 #流量权重
      - pause: {}  # 不填写暂停时间会一直暂停
      - setWeight: 40
      - pause: {duration: 10}  # 暂停时间，单位默认秒
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2  
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      terminationGracePeriodSeconds: 30  # 等待 30 秒来优雅关闭 Pod
      containers:
      - name: rollout-canary
        image: docker.io/dockeraec/nginx:v1  #SWR中提前上传的镜像，版本号为v1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
       #readinessProbe:
       #   httpGet:
       #     path: /
       #     port: 80
       #   initialDelaySeconds: 10
       #   periodSeconds: 5
       # lifecycle:
       #   preStop:
       #     exec:
       #       command: ["sleep","60"]
      #terminationGracePeriodSeconds: 30  # 等待 30 秒来优雅关闭 Pod
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-canary
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31270  #自定义节点端口号
  selector:
    app: rollout-canary
